name: MaX.Studio Gitee repos mirror periodic job

on:
  push:
    branches:
    - main
    schedule:
    # 每天上午七点定时同步（北京时间）
    - cron:  '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@v0.11 # Docker 镜像仓库
      with:
        # 必选，需要同步的Github用户（源）
        src: github/max-studio
        # 必选，需要同步到的Gitee的用户（目的）
        dst: gitee/max-studio
        # 必选，Gitee公钥对应的私钥，https://gitee.com/profile/sshkeys
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        # 必选，Gitee对应的用于创建仓库的token，https://gitee.com/profile/personal_access_tokens
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        # 如果是组织，指定组织即可，默认为用户user
        account_type: org
        # 指定目录生成缓存文件
        cache_path: /github/workspace/hub-mirror-cache
        # 还有黑、白名单，静态名单机制，可以用于更新某些指定库
        # static_list: repo_name
        # 白名单 repo
        white_list: "CMT_CS_Learning"
        # 黑名单 repo
        black_list: "Software-Test-Basis,maxface,LaTeX-Template"
        # 取消码云禁止邮箱暴露
